### PR TITLE
Add sudo for updating apt-cache

### PR DESCRIPTION
**Pull request by misilot**
Enforce using sudo to update apt-cache

### CODE REVIEW

**Comment by hakamine** [comment]
Thank you for the fixes! (didn't notice the missing sudo as I was running the entire role with sudo).
One small request: in commit c5a43ad instead of moving apt: update_cache=true inside the Install python-curl task, could you please put it into a different task (same as in storage-service-packages.yml )? Or if you prefer I'll do the changes

**Comment by misilot** [comment]
I should be able to do that.

**Comment by misilot** [comment]
@hakamine storage-service-packages.yml is already a seperate task. All I did was add sudo to that one.

**Comment by misilot** [comment]
@hakamine Should be fixed as requested.

**Comment by hakamine** [comment]
👍 thank you, sorry it took so long, completely overlooked it.

**Pull request merged**
